### ISSUE TITLE
Vagrant build issue

### ISSUE THREAD

**Issue by Signorini** [fizzed/font-mfizz#63]
I try to build new icons, but i have a problem inside vagrant box.

---------------------/// ----------------------------------------

Expected array default value for '--templates'; got "css preview" (string)
       debug  Using settings from `./src/config.yml`.

...

create  build/font
       debug  Copyright (c) 2000-2012 by George Williams.
               Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
               Library based on sources from 14:57 GMT 31-Jul-2012.
              Failed to parse color
              Failed to parse color

...

Traceback (most recent call last):
                File "/var/lib/gems/1.9.1/gems/fontcustom-1.3.8/lib/fontcustom/scripts/generate.py", line 120, in <module>
                  subprocess.call(['sfnt2woff', fontfile + '.ttf'])
                File "/usr/lib/python2.7/subprocess.py", line 522, in call
                  return Popen(*popenargs, **kwargs).wait()

...

[ERROR] java.io.FileNotFoundException: ./build/font/font-mfizz.css (No such file or directory)
java.lang.RuntimeException: java.io.FileNotFoundException: ./build/font/font-mfizz.css (No such file or directory)
	at org.unix4j.io.FileInput.createFileReader(FileInput.java:119)
	at org.unix4j.io.FileInput.<init>(FileInput.java:32)

---------------------/// ----------------------------------------

I using virtualbox 5.22, any tips to resolve this? Thanks

**Comment by Signorini** [comment]
Maybe this is the problem, https://people-mozilla.org/~jkew/woff/ dont work
