### ISSUE TITLE
Vagrant build fails

### ISSUE THREAD

**Issue by JRSofty** [fizzed/font-mfizz#72]
Attempting to build the project using your Vagrant setup and it fails because it creates the file `./build/font/font-mfizz.new.css` instead of `./build/font/font-mfizz.css` which causes the script to fail with a `java.io.FileNotFoundException ./build/font/font-mfizz.css (no such file or directory)`.

Could you please tell me where in your build configuration can I fix this problem so that I can add my svg?

**Comment by JRSofty** [comment]
Looking through the failure it appears the problem happens in your `blaze.groovy` file line 102. According to the comment it is doing the following:

    // stip first 4 lines of css to new css
    Unix4j
        .tail(Tail.Options.s, 4, cssFile.toFile())
        .toFile(newCssFile.toFile())

The problem here is that the resolution for the variable `cssFile` apparently is not returning the file because it doesn't yet exist. I'm guessing (not a groovy user) that the line `cssFile = fontBuildDir.resolve("font-mfizz.css")` should actually create the missing file, but it doesn't appear to be working, any reason why this file is not being created?

**Comment by JRSofty** [comment]
Found the vagrant bootstrap shell file, and adjusted the download path for sfnt2woff, but apparently who ever is releasing that package does not provide the make file and so the build fails. 

Since I can't figure out how to make your build system work I'm going to attempt to compile it using the FontCustom project alone.

**Comment by Jan-LucaKlees** [comment]
I have the same issue but before the Java error appears Python is throwing something. Here's the log:
```
Traceback (most recent call last):
  File "/var/lib/gems/1.9.1/gems/fontcustom-1.3.8/lib/fontcustom/scripts/generate.py", line 120, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
error  `fontforge` compilation failed.
```

and after that Java comes up with:

```
[ERROR] Problem with script likey @ blaze.groovy:102
[ERROR] java.io.FileNotFoundException: ./build/font/font-mfizz.css (No such file or directory)
```

To me, this looks like it's already failing in the Python part when it looks for the .ttf file. However, in the build dir, there's a font-mfizz.ttf file. So I have no idea what's going on there.

Might it be that it's not only Java to blame here?
